jaffle_shop:
  outputs:
    prod:
      location: europe-west2
      method: oauth
      project: data-sandbox-266217
      schema: bsl
      threads: 4
      type: bigquery
    sandbox_dev:
      location: europe-west2
      method: oauth
      project: data-sandbox-266217
      schema: dbt_bsl
      threads: 4
      type: bigquery
  target: sandbox_dev