steps:
  - name: docker
    env:
    - 'GCS_ARTIFACTS_BUCKET=data-sandbox-266217-misc-data'
    args:
      - build
      - --tag=gcr.io/${_PROJECT_ID}/${_JOB_NAME}
      - --file=./.docker/Dockerfile
      - .
images:
  - gcr.io/${_PROJECT_ID}/${_JOB_NAME}
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _JOB_NAME: dbt-job3